### ISSUE TITLE
提示NVIDIA驱动太老，需要哪个版本以上才能跑起来呢

### ISSUE THREAD

**Issue by Zixiong-Yao** [THUDM/ChatGLM3#100]
RuntimeError: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by yhyu13** [comment]
pip list 看一下torch的版本。

一般更新driver到最新都行？

**Comment by ItsFated** [comment]
[CUDA Toolkit](https://developer.nvidia.com/cuda-toolkit)，直接通过CUDA Toolkit安装，在安装过程中会将驱动安装好。
``` shell
# 安装
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-3
sudo apt-get install -y cuda-drivers
```

**Comment by yhyu13** [comment]
注意上图中ubuntu服务器最后一步需要安装server驱动

sudo apt-get install -y cuda-drivers-server

**Comment by zRzRzRzRzRzRzR** [comment]
社区用户已经解决问题，该issue关闭，如果遇到新问题，请再次提出新的issue
