### ISSUE TITLE
使用inference进行导入出现RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by zcs007** [THUDM/ChatGLM3#1012]
### System Info / 系統信息

cuda: 12.1
Transformers : 4.39.0
python : 3.11.7
os : Linux algo 5.4.0-171-generic

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行!CUDA_VISIBLE_DEVICES=1  python3 inference_hf.py output/checkpoint-3000/ --prompt "类型#裙*版型#显瘦*材质#网纱*风格#性感*裙型#百褶*裙下摆#压褶*裙长#连衣裙*裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则" 命令后出现
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [762,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
 /home/hduser/miniconda3/envs/chat_zjq/lib/python3.11/site-packages/torch/nn/functional.py:2237   │
│ in embedding                                                                                     │
│                                                                                                  │
│   2234 │   │   #   torch.embedding_renorm_                                                       │
│   2235 │   │   # remove once script supports set_grad_enabled                                    │
│   2236 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
│ ❱ 2237 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
│   2238                                                                                           │
│   2239                                                                                           │
│   2240 def embedding_bag(                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Expected behavior / 期待表现

正常导入

**Comment by yutianli2023** [comment]
Hello, also encountered the same issue, and I hope someone can research and find a solution to this problem together. Thank you.

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题能复现吗，我无法复现，看一下依赖

**Comment by yutianli2023** [comment]
用autodl上面的4090跑的，python=3.9，pytorch=2.1，其他依赖如下：
accelerate==0.28.0
aiofiles==23.2.1
aiohttp==3.9.3
aiosignal==1.3.1
altair==5.2.0
annotated-types==0.6.0
anyio==4.3.0
arxiv==2.1.0
async-timeout==4.0.3
attrs==23.2.0
blinker==1.7.0
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cpm-kernels==1.0.11
cycler==0.12.1
dataclasses-json==0.6.4
datasets==2.18.0
dill==0.3.8
distro==1.9.0
exceptiongroup==1.2.0
fastapi==0.110.0
feedparser==6.0.10
ffmpy==0.3.2
filelock==3.13.1
fonttools==4.50.0
frozenlist==1.4.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.42
gradio==4.22.0
gradio_client==0.13.0
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
huggingface-hub==0.21.4
idna==3.6
importlib_metadata==7.1.0
importlib_resources==6.4.0
jieba==0.42.1
Jinja2==3.1.3
joblib==1.3.2
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter_client==8.6.1
jupyter_core==5.7.2
kiwisolver==1.4.5
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.33
langchain-text-splitters==0.0.1
langchainhub==0.1.15
langsmith==0.1.31
latex2mathml==3.77.0
loguru==0.7.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.1
matplotlib==3.8.3
mdtex2html==1.3.0
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
mypy-extensions==1.0.0
networkx==3.2.1
nltk==3.8.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
openai==1.14.2
orjson==3.9.15
packaging==23.2
pandas==2.2.1
peft==0.10.0
pillow==10.2.0
platformdirs==4.2.0
protobuf==4.25.3
psutil==5.9.8
pyarrow==15.0.2
pyarrow-hotfix==0.6
pydantic==2.6.4
pydantic_core==2.16.3
pydeck==0.8.1b0
pydub==0.25.1
Pygments==2.17.2
PyJWT==2.8.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
referencing==0.34.0
regex==2023.12.25
requests==2.31.0
rich==13.7.1
rouge-chinese==1.0.3
rpds-py==0.18.0
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
ruff==0.3.4
safetensors==0.4.2
scikit-learn==1.4.1.post1
scipy==1.12.0
semantic-version==2.10.0
sentence-transformers==2.5.1
sentencepiece==0.2.0
sgmllib3k==1.0.0
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
SQLAlchemy==2.0.28
sse-starlette==2.0.0
starlette==0.36.3
streamlit==1.32.2
sympy==1.12
tenacity==8.2.3
threadpoolctl==3.4.0
tiktoken==0.6.0
timm==0.9.16
tokenizers==0.15.2
toml==0.10.2
tomlkit==0.12.0
toolz==0.12.1
torch==2.2.1
torchvision==0.17.1
tornado==6.4
tqdm==4.66.2
traitlets==5.14.2
transformers==4.39.0
triton==2.2.0
typer==0.9.0
types-requests==2.31.0.20240311
typing-inspect==0.9.0
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
uvicorn==0.29.0
watchdog==4.0.0
websockets==11.0.3
xxhash==3.4.1
yarl==1.9.4
zhipuai==2.0.1
zipp==3.18.1
如能解决，给个方案，谢谢大佬Thanks♪(･ω･)ﾉ

**Comment by lijialeplus** [comment]
transformers==4.38.1
peft==0.7.1

**Comment by zRzRzRzRzRzRzR** [comment]
最新的脚本可以不用pef 0.7.1 啊，我训练了一下好像没问题，不过0.7.1是最稳定额

**Comment by Dongru1** [comment]
我也遇到了同样的情况！重新安装0.7.1再训练，推理才正常的。

> transformers==4.38.1 peft==0.7.1 你需要重新训练

**Comment by yutianli2023** [comment]
> transformers==4.38.1 peft==0.7.1 你需要重新训练

确实，重装这两依赖就重新训练就正常操作了，谢谢各位小伙伴的热心帮助，谢谢 @lijialeplus @Dongru1 @zRzRzRzRzRzRzR @zcs007 。

**Comment by zcs007** [comment]
解决了，conda的编译工具版本升级，导致没找到，更改下就可以了

**Comment by sanbei011** [comment]
我也遇到了相同的问题!

**Comment by BruceJust** [comment]
> 解决了，conda的编译工具版本升级，导致没找到，更改下就可以了

说的不明白啊，大家每天还在重复出现，官方给个详细的配置解决方案吧，glm4也一样遇到
