### ISSUE TITLE
composite_demo OOM

### ISSUE THREAD

**Issue by FlatMapIO** [THUDM/ChatGLM3#84]
我使用 chatglm3-6b 的模型， web_demo.py 运行时只用到 12G 左右的 VRAM， 但是 composite_demo 在启动时会直接 OOM，为何 composite_demo 需要如此多的 VRAM， 26G 卡无法使用吗？

**Comment by Bean95zx** [comment]
你看下是不是import demo_cli+import demo_chat+import tool 注释掉部分就好了，我发现这三个会导入三次模型

**Comment by FlatMapIO** [comment]
改了 get_client, 似乎不会反复加载模型了, 但还是运行不起来
```python

    2 ▎ client = HFClient(MODEL_PATH)
    1 ▎ @st.cache_resource
  137 ▎ def get_client() -> Client:
    1 ▎ │   return client
```


```
2023-11-01 11:29:27.474
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run composite_demo/main.py [ARGUMENTS]
[registered tool] {'description': 'Generates a random number x, s.t. range[0] <= x < range[1]',
 'name': 'random_number_generator',
 'params': [{'description': 'The random seed used by the generator',
             'name': 'seed',
             'required': True,
             'type': 'int'},
            {'description': 'The range of the generated numbers',
             'name': 'range',
             'required': True,
             'type': 'tuple[int, int]'}]}
[registered tool] {'description': 'Get the current weather for `city_name`',
 'name': 'get_weather',
 'params': [{'description': 'The name of the city to be queried',
             'name': 'city_name',
             'required': True,
             'type': 'str'}]}
2023-11-01 11:29:27.497 Session state does not function when running a script without `streamlit run`
Traceback (most recent call last):
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 394, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 439, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 119, in __getattr__
    return self[key]
           ~~~~^^^^^
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 89, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 396, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "chat_history". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sa/Workspace/llm/ChatGLM3/composite_demo/main.py", line 50, in <module>
    demo_chat.main(top_p, temperature, system_prompt, prompt_text)
  File "/home/sa/Workspace/llm/ChatGLM3/composite_demo/demo_chat.py", line 26, in main
    history: list[Conversation] = st.session_state.chat_history
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sa/miniconda3/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "chat_history". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

**Comment by FlatMapIO** [comment]
需要使用 streamlib 才能正确启动, 露看文档了. 

```
streamlit run main.py
```
