### ISSUE TITLE
单机多卡微调卡住不动

### ISSUE THREAD

**Issue by xtanitfy** [THUDM/ChatGLM3#890]
OMP_NUM_THREADS=1 torchrun --standalone  --nnodes=1 --nproc_per_node=2  finetune_hf.py  ../train/data/  ../weights/chatglm3-6b  my_configs/lora.yaml

单机两个2080TI，使用上述命令，除了打印一行就一直卡住不动了：
[2024-02-28 11:22:08,273] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.

**Comment by zRzRzRzRzRzRzR** [comment]
这个是硬件问题么，我咋没遇到，你有cuda设备吗

**Comment by xtanitfy** [comment]
肯定有的我已经调通了Qwen 7b-4bit的qlora微调训练，数据较少，之前的就遗忘了，昨天看到你们这个就也想试试，聊天速度还是挺快的，nvidia-smi：
(base) shawn@compute2:~$ nvidia-smi
Wed Feb 28 12:05:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:01:00.0  On |                  N/A |
| 30%   40C    P8              19W / 250W |    115MiB / 11264MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:03:00.0 Off |                  N/A |
| 30%   36C    P8              29W / 250W |      8MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by xtanitfy** [comment]
> 肯定有的我已经调通了Qwen 7b-4bit的qlora微调训练，数据较少，训练之后严重过拟合，它把之前的全遗忘了，昨天看到你们这个就也想试试，聊天速度还是挺快的，nvidia-smi： (base) shawn@compute2:~$ nvidia-smi Wed Feb 28 12:05:15 2024 +---------------------------------------------------------------------------------------+ | NVIDIA-SMI 535.154.05 Driver Version: 535.154.05 CUDA Version: 12.2 | |-----------------------------------------+----------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+======================+======================| | 0 NVIDIA GeForce RTX 2080 Ti Off | 00000000:01:00.0 On | N/A | | 30% 40C P8 19W / 250W | 115MiB / 11264MiB | 1% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 1 NVIDIA GeForce RTX 2080 Ti Off | 00000000:03:00.0 Off | N/A | | 30% 36C P8 29W / 250W | 8MiB / 11264MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+
> 
> (glm3) shawn@compute2:~/diska/samba/Train/BIgmode/ChatGLM3/ChatGLM3-main/finetune_demo$ pip list Package Version
> 
> accelerate 0.27.2 aiofiles 23.2.1 aiohttp 3.9.3 aiosignal 1.3.1 altair 5.2.0 annotated-types 0.6.0 anyio 4.3.0 argon2-cffi 23.1.0 argon2-cffi-bindings 21.2.0 arrow 1.3.0 arxiv 2.1.0 asttokens 2.4.1 async-lru 2.0.4 attrs 23.2.0 Babel 2.14.0 beautifulsoup4 4.12.3 bleach 6.1.0 blinker 1.7.0 cachetools 5.3.3 certifi 2022.12.7 cffi 1.16.0 charset-normalizer 2.1.1 click 8.1.7 colorama 0.4.6 comm 0.2.1 contourpy 1.2.0 cpm-kernels 1.0.11 cycler 0.12.1 dataclasses-json 0.6.4 datasets 2.17.1 debugpy 1.8.1 decorator 5.1.1 deepspeed 0.13.4 defusedxml 0.7.1 dill 0.3.8 distro 1.9.0 executing 2.0.1 fastapi 0.110.0 fastjsonschema 2.19.1 feedparser 6.0.10 ffmpy 0.3.2 filelock 3.9.0 fonttools 4.49.0 fqdn 1.5.1 frozenlist 1.4.1 fsspec 2023.10.0 gitdb 4.0.11 GitPython 3.1.42 gradio 4.19.2 gradio_client 0.10.1 greenlet 3.0.3 h11 0.14.0 hjson 3.1.0 httpcore 1.0.4 httpx 0.27.0 huggingface-hub 0.21.1 idna 3.4 importlib-metadata 7.0.1 importlib_resources 6.1.2 ipykernel 6.29.3 ipython 8.22.1 ipywidgets 8.1.2 isoduration 20.11.0 jedi 0.19.1 jieba 0.42.1 Jinja2 3.1.2 joblib 1.3.2 json5 0.9.17 jsonpatch 1.33 jsonpointer 2.4 jsonschema 4.21.1 jsonschema-specifications 2023.12.1 jupyter 1.0.0 jupyter_client 8.6.0 jupyter-console 6.6.3 jupyter_core 5.7.1 jupyter-events 0.9.0 jupyter-lsp 2.2.3 jupyter_server 2.12.5 jupyter_server_terminals 0.5.2 jupyterlab 4.1.2 jupyterlab_pygments 0.3.0 jupyterlab_server 2.25.3 jupyterlab_widgets 3.0.10 kiwisolver 1.4.5 langchain 0.1.9 langchain-community 0.0.24 langchain-core 0.1.27 langchainhub 0.1.14 langsmith 0.1.10 latex2mathml 3.77.0 loguru 0.7.2 Markdown 3.5.2 markdown-it-py 3.0.0 MarkupSafe 2.1.3 marshmallow 3.21.0 matplotlib 3.8.3 matplotlib-inline 0.1.6 mdtex2html 1.3.0 mdurl 0.1.2 mistune 3.0.2 mpi4py 3.1.5 mpmath 1.3.0 multidict 6.0.5 multiprocess 0.70.16 mypy-extensions 1.0.0 nbclient 0.9.0 nbconvert 7.16.1 nbformat 5.9.2 nest-asyncio 1.6.0 networkx 3.2.1 ninja 1.11.1.1 nltk 3.8.1 notebook 7.1.1 notebook_shim 0.2.4 numpy 1.26.3 openai 1.12.0 orjson 3.9.15 overrides 7.7.0 packaging 23.2 pandas 2.2.1 pandocfilters 1.5.1 parso 0.8.3 peft 0.7.1 pexpect 4.9.0 pillow 10.2.0 pip 23.3.1 platformdirs 4.2.0 prometheus_client 0.20.0 prompt-toolkit 3.0.43 protobuf 4.25.3 psutil 5.9.8 ptyprocess 0.7.0 pure-eval 0.2.2 py-cpuinfo 9.0.0 pyarrow 15.0.0 pyarrow-hotfix 0.6 pycparser 2.21 pydantic 2.6.3 pydantic_core 2.16.3 pydeck 0.8.1b0 pydub 0.25.1 Pygments 2.17.2 PyJWT 2.8.0 pynvml 11.5.0 pyparsing 3.1.1 python-dateutil 2.8.2 python-json-logger 2.0.7 python-multipart 0.0.9 pytz 2024.1 PyYAML 6.0.1 pyzmq 25.1.2 qtconsole 5.5.1 QtPy 2.4.1 referencing 0.33.0 regex 2023.12.25 requests 2.31.0 rfc3339-validator 0.1.4 rfc3986-validator 0.1.1 rich 13.7.0 rouge-chinese 1.0.3 rpds-py 0.18.0 ruamel.yaml 0.18.6 ruamel.yaml.clib 0.2.8 ruff 0.2.2 safetensors 0.4.2 scikit-learn 1.4.1.post1 scipy 1.12.0 semantic-version 2.10.0 Send2Trash 1.8.2 sentence-transformers 2.4.0 sentencepiece 0.2.0 setuptools 68.2.2 sgmllib3k 1.0.0 shellingham 1.5.4 six 1.16.0 smmap 5.0.1 sniffio 1.3.1 soupsieve 2.5 SQLAlchemy 2.0.27 sse-starlette 2.0.0 stack-data 0.6.3 starlette 0.36.3 streamlit 1.31.1 sympy 1.12 tenacity 8.2.3 terminado 0.18.0 threadpoolctl 3.3.0 tiktoken 0.6.0 timm 0.9.16 tinycss2 1.2.1 tokenizers 0.15.2 toml 0.10.2 tomlkit 0.12.0 toolz 0.12.1 torch 2.1.0+cu118 torchaudio 2.1.0+cu118 torchvision 0.16.0+cu118 tornado 6.4 tqdm 4.66.2 traitlets 5.14.1 transformers 4.38.1 triton 2.1.0 typer 0.9.0 types-python-dateutil 2.8.19.20240106 types-requests 2.31.0.20240218 typing_extensions 4.8.0 typing-inspect 0.9.0 tzdata 2024.1 tzlocal 5.2 uri-template 1.3.0 urllib3 2.2.1 uvicorn 0.27.1 validators 0.22.0 watchdog 4.0.0 wcwidth 0.2.13 webcolors 1.13 webencodings 0.5.1 websocket-client 1.7.0 websockets 11.0.3 wheel 0.41.2 widgetsnbextension 4.0.10 xxhash 3.4.1 yarl 1.9.4 zhconv 1.4.3 zhipuai 2.0.1 zipp 3.17.0

我猜测我的显卡是2080TI太旧导致一些加速的东西不支持卡到某个地方也不报错也不退出

**Comment by xtanitfy** [comment]
torchrun  --nproc_per_node 2 --nnodes 1 --node_rank 0 --master_addr localhost --master_port 6001 \
finetune_hf.py  ../train/data/AdvertiseGen  \
../weights/chatglm3-6b  my_configs/lora.yaml  \
--deepspeed my_configs/ds_zero_2.json 
使用readme里边的数据，同样也是有错误，注意我这里不能加 --standalone，必须按照上面的torchrun参数才能运行否则一直卡住使用上述命令出错如下：
[2024-02-28 12:49:23,439] torch.distributed.run: [WARNING] 
[2024-02-28 12:49:23,439] torch.distributed.run: [WARNING] *****************************************
[2024-02-28 12:49:23,439] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-02-28 12:49:23,439] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/home/shawn/diska/samba/Train/BIgmode/ChatGLM3/ChatGLM3-main/finetune_demo/finetune_hf.py", line 146, in <module>
    @dc.dataclass
     ^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'transformers.training_args_seq2seq.Seq2SeqTrainingArguments'> for field training_args is not allowed: use default_factory
Traceback (most recent call last):
  File "/home/shawn/diska/samba/Train/BIgmode/ChatGLM3/ChatGLM3-main/finetune_demo/finetune_hf.py", line 146, in <module>
    @dc.dataclass
     ^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'transformers.training_args_seq2seq.Seq2SeqTrainingArguments'> for field training_args is not allowed: use default_factory
[2024-02-28 12:49:28,441] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 11949) of binary: /home/shawn/diska/anaconda/envs/glm3/bin/python
Traceback (most recent call last):
  File "/home/shawn/diska/anaconda/envs/glm3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/diska/anaconda/envs/glm3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune_hf.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-28_12:49:28
  host      : compute2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11950)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-28_12:49:28
  host      : compute2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11949)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by xtanitfy** [comment]
问题已经解决，我用Qwen的coda环境就不会出错了，现在的问题是显存不够了，

**Comment by sevenandseven** [comment]
> OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 finetune_hf.py ../train/data/ ../weights/chatglm3-6b my_configs/lora.yaml
> 
> 单机两个2080TI，使用上述命令，除了打印一行就一直卡住不动了： [2024-02-28 11:22:08,273] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.

你好，我想请问一下，关于使用deepspeed进行单机多卡加速，相关代码在哪里，没有看到实现这个功能的代码？
